//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedNAVHost {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedNAVHost.MainFormStrings", typeof(MainFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buoy.
        /// </summary>
        internal static string mfText_BuoyStr {
            get {
                return ResourceManager.GetString("mfText_BuoyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting.
        /// </summary>
        internal static string mfText_CennectingStr {
            get {
                return ResourceManager.GetString("mfText_CennectingStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all points?.
        /// </summary>
        internal static string mfText_ClearAllPointsStr {
            get {
                return ResourceManager.GetString("mfText_ClearAllPointsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List is empty. Continue and clear all waypoints and saved points in your RedNAV device?.
        /// </summary>
        internal static string mfText_ClearWaypointsAndContinueStr {
            get {
                return ResourceManager.GetString("mfText_ClearWaypointsAndContinueStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string mfText_CloseAppQuestionStr {
            get {
                return ResourceManager.GetString("mfText_CloseAppQuestionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        internal static string mfText_ConnectedStr {
            get {
                return ResourceManager.GetString("mfText_ConnectedStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to core.
        /// </summary>
        internal static string mfText_CoreStr {
            get {
                return ResourceManager.GetString("mfText_CoreStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        internal static string mfText_DataBaseErrorStr {
            get {
                return ResourceManager.GetString("mfText_DataBaseErrorStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device track contains.
        /// </summary>
        internal static string mfText_DeviceTrackContainsStr {
            get {
                return ResourceManager.GetString("mfText_DeviceTrackContainsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device track is empty.
        /// </summary>
        internal static string mfText_DeviceTrackIsEmptyStr {
            get {
                return ResourceManager.GetString("mfText_DeviceTrackIsEmptyStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device version.
        /// </summary>
        internal static string mfText_DeviceVersionStr {
            get {
                return ResourceManager.GetString("mfText_DeviceVersionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving data to.
        /// </summary>
        internal static string mfText_ErrorSavingDataStr {
            get {
                return ResourceManager.GetString("mfText_ErrorSavingDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string mfText_FindStr {
            get {
                return ResourceManager.GetString("mfText_FindStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string mfText_LatitudeStr {
            get {
                return ResourceManager.GetString("mfText_LatitudeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string mfText_LongitudeStr {
            get {
                return ResourceManager.GetString("mfText_LongitudeStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigational receiver.
        /// </summary>
        internal static string mfText_NavigationalReceiverStr {
            get {
                return ResourceManager.GetString("mfText_NavigationalReceiverStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearest.
        /// </summary>
        internal static string mfText_NearestStr {
            get {
                return ResourceManager.GetString("mfText_NearestStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string mfText_NoDataStr {
            get {
                return ResourceManager.GetString("mfText_NoDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No track data is availible.
        /// </summary>
        internal static string mfText_NoTrackDataAvailible {
            get {
                return ResourceManager.GetString("mfText_NoTrackDataAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own track.
        /// </summary>
        internal static string mfText_OwnTrackStr {
            get {
                return ResourceManager.GetString("mfText_OwnTrackStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        internal static string mfText_pointsStr {
            get {
                return ResourceManager.GetString("mfText_pointsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string mfText_QuestionStr {
            get {
                return ResourceManager.GetString("mfText_QuestionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove track from RedNAV device?.
        /// </summary>
        internal static string mfText_RemoveTrackFromDeviceStr {
            get {
                return ResourceManager.GetString("mfText_RemoveTrackFromDeviceStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity adjust.
        /// </summary>
        internal static string mfText_SalinityAdjustStr {
            get {
                return ResourceManager.GetString("mfText_SalinityAdjustStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity, PPM.
        /// </summary>
        internal static string mfText_SalinityPPMStr {
            get {
                return ResourceManager.GetString("mfText_SalinityPPMStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved point.
        /// </summary>
        internal static string mfText_SavedPoint {
            get {
                return ResourceManager.GetString("mfText_SavedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching for a RedNAV device....
        /// </summary>
        internal static string mfText_SearchingForDeviceStr {
            get {
                return ResourceManager.GetString("mfText_SearchingForDeviceStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string mfText_WaypointStr {
            get {
                return ResourceManager.GetString("mfText_WaypointStr", resourceCulture);
            }
        }
    }
}
